#!/usr/bin/env python3
"""Generate fig1/fig2/fig3 (PDF + preview PNG) for the Letter.

Every number is computed from the exact equations or read from the committed
scan JSONs — no hand-entered data:
  fig2: S12(k1,k2) = -(e^{i(k1+k2)} - 2 e^{ik1} + 1)/(e^{i(k1+k2)} - 2 e^{ik2} + 1)
        (theory/oracle-bethe.md eq. (6), D7 convention), plus
        numerics/results/fm-displacement-scan.json (wavepacket measurements).
  fig3: numerics/results/memory-scan-1.json (delta-x, T, R),
        R_pred = x/(1+x), x = J^4/(16 omega^2 v^2), omega = J(Delta - cos k),
        v = J sin k (theory/corner-b-draft.md), and
        paper/figures/profile-D3.0-k1.2.json (space-time record, generated by
        make_profile_data.jl from the committed TriangleMPS code).
Palette: dataviz reference palette, validated on white via validate_palette.js
        (ordinal blue ramps; categorical blue/orange/aqua; diverging blue-red).
"""
import json
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Circle, Rectangle, FancyArrowPatch

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

# ---------------------------------------------------------------- style ----
INK = "#0b0b0b"; INK2 = "#52514e"; MUTED = "#898781"; BASE = "#c3c2b7"
BLUE, ORANGE, AQUA, RED = "#2a78d6", "#eb6834", "#1baf7a", "#e34948"
RAMP3 = ["#86b6ef", "#2a78d6", "#104281"]            # ordinal, validated
RAMP5 = ["#86b6ef", "#5598e7", "#2a78d6", "#1c5cab", "#104281"]
NEUTRAL_MID = "#f0efec"

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["STIXGeneral", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 8,
    "axes.labelsize": 8,
    "axes.titlesize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 7,
    "axes.linewidth": 0.6,
    "axes.edgecolor": INK2,
    "axes.labelcolor": INK,
    "xtick.color": INK2, "ytick.color": INK2,
    "xtick.direction": "in", "ytick.direction": "in",
    "xtick.top": True, "ytick.right": True,
    "xtick.major.size": 2.6, "ytick.major.size": 2.6,
    "xtick.major.width": 0.6, "ytick.major.width": 0.6,
    "lines.linewidth": 1.1,
    "savefig.dpi": 300,
    "pdf.fonttype": 42,
})
W = 3.375  # single column, inches


def save(fig, name):
    fig.savefig(os.path.join(HERE, f"{name}.pdf"))
    fig.savefig(os.path.join(HERE, f"{name}.png"), dpi=200)
    plt.close(fig)
    print(f"wrote {name}.pdf/.png")


# ------------------------------------------------------- exact equations ----
def S12(ks, kh):
    """theory/oracle-bethe.md eq. (6), D7 ordering (soft = k1, hard = k2)."""
    z12 = np.exp(1j * (ks + kh))
    return -(z12 - 2 * np.exp(1j * ks) + 1) / (z12 - 2 * np.exp(1j * kh) + 1)


def delta_phase(ks_grid, kh):
    """Continuous branch of arg S12 with delta(0)=0 (D7)."""
    ph = np.unwrap(np.angle(S12(ks_grid, kh)))
    i0 = np.argmin(np.abs(ks_grid))
    return ph - ph[i0]


def displacement(ks_grid, kh):
    """Soft packet exit displacement -d(delta)/d(k_s) (D7 sign convention,
    matching fm-displacement-scan.json)."""
    d = delta_phase(ks_grid, kh)
    return -np.gradient(d, ks_grid)


def R_pred(k, Delta, J=1.0):
    """theory/corner-b-draft.md: R = x/(1+x), x = J^4/(16 omega^2 v^2)."""
    om = J * (Delta - np.cos(k)); v = J * np.sin(k)
    x = J**4 / (16.0 * om**2 * v**2)
    return x / (1.0 + x)


# ---------------------------------------------------------------- data ----
with open(os.path.join(REPO, "numerics/results/fm-displacement-scan.json")) as f:
    FM = json.load(f)["summary"]
with open(os.path.join(REPO, "numerics/results/memory-scan-1.json")) as f:
    MEM = json.load(f)["runs"]


def mem_rows(prefix):
    out = []
    for r in MEM:
        if r["label"].startswith(prefix):
            res = r["result"]; p = res["params"]
            out.append(dict(Delta=float(p["Delta"]), k0=float(p["k0"]),
                            dx=float(res["dx2"]), T=float(res["transmission"]),
                            R=float(res["reflection"])))
    return out


# ================================================================= FIG 2 ====
def fig2():
    fig, (a, b) = plt.subplots(
        2, 1, figsize=(W, 4.0), height_ratios=[1.0, 1.35],
        gridspec_kw=dict(hspace=0.32, left=0.155, right=0.97, top=0.965, bottom=0.095))
    ks = np.linspace(-0.36, 0.36, 1201)
    khs = [0.8, 1.5, 2.4]

    # (a) the remainder delta - 2 k_s: hard data enters only at O(k_s^2)
    a.axhline(0, ls="--", color=INK, lw=0.9, zorder=2)
    a.plot(ks, delta_phase(ks, 0.4) - 2 * ks, color=MUTED, lw=0.9, zorder=2)
    for kh, c in zip(khs, RAMP3):
        a.plot(ks, delta_phase(ks, kh) - 2 * ks, color=c, zorder=3)
    a.text(0.03, 0.05, r"universal part $2k_s$ removed", fontsize=7,
           color=INK, transform=a.transAxes)
    a.annotate(r"$\frac{v_h}{\omega_h}k_s^2$", xy=(0.255, delta_phase(np.array([0.255, 0.2551, 0.2552]), 0.8)[0] - 2 * 0.255),
               xytext=(0.13, 0.115), color=INK, fontsize=8,
               arrowprops=dict(arrowstyle="-", lw=0.5, color=MUTED))
    a.text(-0.20, 0.125, r"$k_h=0.4$", color=MUTED, fontsize=7)
    a.text(-0.325, 0.056, r"$0.8$", color=RAMP3[0], fontsize=7)
    a.text(-0.325, 0.028, r"$1.5$", color=RAMP3[1], fontsize=7)
    a.set_xlim(-0.36, 0.36); a.set_ylim(-0.16, 0.16)
    a.set_ylabel(r"$\delta(k_s,k_h)-2k_s$")
    a.set_xlabel(r"$k_s$", labelpad=1)
    a.text(0.03, 0.88, "(a)", transform=a.transAxes, fontsize=8, color=INK)

    # (b) exit displacement: pencil of curves through (0, -2)
    b.axhline(-2, ls="--", color=INK, lw=0.9, zorder=1)
    ksd = np.linspace(-0.36, 0.36, 1201)
    b.plot(ksd, displacement(ksd, 0.4), color=MUTED, lw=0.9, zorder=2)
    for kh, c in zip(khs, RAMP3):
        b.plot(ksd, displacement(ksd, kh), color=c, zorder=3)
    # wavepacket measurements (real-time dynamics)
    for r in FM:
        kh = r["k_h"]
        c = {0.8: RAMP3[0], 1.5: RAMP3[1], 2.4: RAMP3[2], 0.4: MUTED, 3.0: "#6b3fa0"}.get(kh)
        if c is None or kh == 3.0:
            continue
        b.errorbar(r["k_s"], r["displacement_soft_measured"],
                   yerr=r["displacement_soft_error"], fmt="o", ms=3.4,
                   mfc="white", mec=c, mew=0.9, ecolor=c, elinewidth=0.7,
                   capsize=1.5, zorder=4)
    # direct labels
    b.text(0.300, -2.02, r"$k_h=2.4$", color=RAMP3[2], fontsize=7, va="bottom")
    b.text(0.305, -2.52, r"$1.5$", color=RAMP3[1], fontsize=7, va="bottom")
    b.text(0.305, -3.28, r"$0.8$", color=RAMP3[0], fontsize=7, va="bottom")
    b.text(0.055, -4.55, r"$0.4$", color=MUTED, fontsize=7)
    b.annotate("universal:\n$-2$ sites", xy=(-0.27, -2.0), xytext=(-0.335, -2.95),
               color=INK, fontsize=7.5, ha="left",
               arrowprops=dict(arrowstyle="-", lw=0.5, color=MUTED))
    b.set_xlim(-0.36, 0.36); b.set_ylim(-5.15, -1.2)
    b.set_xlabel(r"soft momentum $k_s$", labelpad=1)
    b.set_ylabel(r"exit displacement $-\partial\delta/\partial k_s$  (sites)")
    b.text(0.03, 0.92, "(b)", transform=b.transAxes, fontsize=8, color=INK)
    save(fig, "fig2")


# ================================================================= FIG 3 ====
def fig3():
    have_prof = os.path.exists(os.path.join(HERE, "profile-D3.0-k1.2.json"))
    rows = [4.6, 3.2, 3.2] if have_prof else [3.2, 3.2]
    fig = plt.figure(figsize=(W, 4.9 if have_prof else 3.6))
    gs = fig.add_gridspec(len(rows), 1, height_ratios=rows,
                          left=0.155, right=0.97, top=0.97, bottom=0.075,
                          hspace=0.42)
    axes = [fig.add_subplot(g) for g in gs]
    ia = 0

    # (a) space-time record of one transmission event: flipped-spin density
    if have_prof:
        with open(os.path.join(HERE, "profile-D3.0-k1.2.json")) as f:
            P = json.load(f)
        t = np.array(P["t"])
        sz = np.array(P["sz"])          # frames x sites
        dens = 0.5 - np.abs(sz)         # one-flipped-spin density (exact)
        # crossing estimator X3 computed from the saved frames (the JSON's
        # wall column is NaN due to a window-arg bug in the generator; same
        # estimator, recomputed here)
        def crossing(m, lo=60, hi=110):
            for x in range(lo, hi):
                if m[x] >= 0 > m[x + 1]:
                    return x + 1 + m[x] / (m[x] - m[x + 1])   # 1-based site
            return np.nan
        wall = np.array([crossing(m) for m in sz])
        x0, x1 = 34, 126
        cmap = LinearSegmentedColormap.from_list(
            "dens", ["#ffffff", "#cde2fb", "#5598e7", "#1c5cab", "#0d366b"])
        ax = axes[ia]; ia += 1
        im = ax.imshow(dens[:, x0:x1], origin="lower", aspect="auto",
                       extent=[x0 + 1, x1, t[0], t[-1]], cmap=cmap,
                       norm=matplotlib.colors.PowerNorm(gamma=0.42, vmin=0, vmax=0.5),
                       interpolation="nearest", rasterized=True)
        tc = P["params"]["tcollision"]
        pre = t < 0.6 * tc
        w0 = wall[pre].mean()
        ax.text(52, 12, "magnon in", color=INK, fontsize=7)
        ax.text(97, 60, "out", color=INK, fontsize=7)
        # zoom inset: the wall trajectory and its -2-site jump
        axi = ax.inset_axes([0.035, 0.52, 0.26, 0.44])
        axi.plot(np.full_like(t, w0), t, ls="--", color=MUTED, lw=0.8)
        axi.plot(wall, t, color=ORANGE, lw=1.1)
        axi.set_xlim(w0 - 3.6, w0 + 1.6); axi.set_ylim(t[0], t[-1])
        axi.set_xticks([w0 - 2, w0]); axi.set_xticklabels(["$-2$", "$0$"], fontsize=6)
        axi.set_yticks([])
        for sp in axi.spines.values():
            sp.set_linewidth(0.5); sp.set_color(INK2)
        axi.tick_params(width=0.5, length=1.8, labelsize=6)
        axi.set_title("wall position", fontsize=6, pad=1.5, color=INK)
        cb = fig.colorbar(im, ax=ax, pad=0.02, fraction=0.055, ticks=[0, 0.1, 0.3, 0.5])
        cb.ax.tick_params(labelsize=6, width=0.5, length=2)
        cb.set_label(r"$\frac{1}{2}-|\langle S^z_x\rangle|$", fontsize=7, labelpad=1)
        cb.outline.set_linewidth(0.5)
        ax.set_xlabel(r"site $x$", labelpad=1)
        ax.set_ylabel(r"time $tJ_\perp$")
        ax.text(0.315, 0.90, "(a)", transform=ax.transAxes, fontsize=8, color=INK)

    # (b) quantized memory: delta-x, -2T, and the analytic curve
    ax = axes[ia]; ia += 1
    ax.axhline(-2, ls="--", color=INK, lw=0.8, zorder=1)
    kk = np.linspace(0.32, 1.9, 300)
    for pref, c, m, lab in [("main-D2.0", BLUE, "o", r"$\Delta=2$"),
                            ("main-D3.0", ORANGE, "s", r"$\Delta=3$")]:
        D = float(pref.split("D")[1])
        ax.plot(kk, -2 * (1 - R_pred(kk, D)), color=c, lw=0.8, alpha=0.75,
                zorder=2)
        rs = sorted(mem_rows(pref), key=lambda r: r["k0"])
        k0 = [r["k0"] for r in rs]
        ax.plot(k0, [r["dx"] for r in rs], m, ms=3.6, color=c, mew=0,
                label=lab, zorder=4)
        ax.plot(k0, [-2 * r["T"] for r in rs], m, ms=6.8, mfc="none", mec=c,
                mew=0.8, ls="none", zorder=3)
    ax.set_xlim(0.3, 1.92); ax.set_ylim(-2.09, -1.38)
    ax.set_xlabel(r"magnon momentum $k_0$", labelpad=1)
    ax.set_ylabel(r"$\delta x$  (sites)")
    ax.text(0.02, 0.18, "(b)", transform=ax.transAxes, fontsize=8, color=INK)
    ax.legend(frameon=False, loc="upper right", handletextpad=0.2,
              borderaxespad=0.4, labelspacing=0.3)
    ax.text(0.975, 0.60, "filled: $\\delta x$\nopen: $-2T(k_0)$\nlines: analytic",
            transform=ax.transAxes, fontsize=6.8, color=INK2, ha="right",
            va="top")

    # (c) parameter-free Fano collapse, all Delta
    ax = axes[ia]
    Ds = [1.5, 2.0, 3.0, 6.0, 12.0]
    marks = ["o", "s", "D", "^", "v"]
    allrows = mem_rows("main-") + mem_rows("Dscan-")
    grid = np.logspace(-3.6, -0.4, 200)
    ax.plot(grid, grid, color=INK, lw=0.8, zorder=1)
    for D, c, m in zip(Ds, RAMP5, marks):
        rs = [r for r in allrows if abs(r["Delta"] - D) < 1e-9]
        if not rs:
            continue
        xs = [R_pred(r["k0"], r["Delta"]) for r in rs]
        ys = [r["R"] for r in rs]
        ax.plot(xs, ys, m, ms=3.6, color=c, mew=0, zorder=3,
                label=rf"$\Delta={D:g}$")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel(r"$R_{\rm pred}=[1+(4\omega v/J_\perp^2)^2]^{-1}$ (no fit)",
                  labelpad=1)
    ax.set_ylabel(r"measured $R$")
    ax.text(0.02, 0.88, "(c)", transform=ax.transAxes, fontsize=8, color=INK)
    ax.legend(frameon=False, loc="lower right", fontsize=6.5,
              handletextpad=0.1, borderaxespad=0.2, labelspacing=0.25)
    save(fig, "fig3")


# ================================================================= FIG 1 ====
def draw_mps(ax, x0, y0, n, r=0.024, dx=0.070, bonds=None, string=None,
             accent=BLUE):
    """A row of MPS tensors with physical legs; optional symmetry string
    (list of site indices carrying u(g)) or bond insertions (list of bond
    indices carrying V labels)."""
    xs = [x0 + i * dx for i in range(n)]
    ax.plot([xs[0] - 0.6 * dx, xs[-1] + 0.6 * dx], [y0, y0], color=INK2,
            lw=0.9, zorder=1, solid_capstyle="round")
    for i, x in enumerate(xs):
        ax.plot([x, x], [y0 + r, y0 + 2.4 * r], color=INK2, lw=0.9, zorder=1)
        ax.add_patch(Circle((x, y0), r, fc="white", ec=INK, lw=0.9, zorder=2))
    if string is not None:
        for i in string:
            x = xs[i]
            ax.add_patch(Rectangle((x - 0.55 * r, y0 + 2.4 * r), 1.1 * r, 1.5 * r,
                                   fc=accent, ec="none", zorder=3))
    if bonds is not None:
        for i, lab in bonds:
            xb = (xs[i] + xs[i + 1]) / 2
            ax.add_patch(Rectangle((xb - 0.7 * r, y0 - 0.7 * r), 1.4 * r, 1.4 * r,
                                   fc=accent, ec="none", zorder=3))
    return xs


def fig1():
    fig, ax = plt.subplots(figsize=(W, 3.05))
    fig.subplots_adjust(left=0.01, right=0.99, top=0.99, bottom=0.01)
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")

    # --- corner A (top): string -> bond insertions --------------------------
    xs = draw_mps(ax, 0.20, 0.895, 7, string=[2, 3, 4], accent=BLUE)
    ax.text(xs[-1] + 0.075, 0.895 + 0.055, r"$\prod_{x\in R}\! u_x(g)$",
            ha="left", va="center", fontsize=7.5, color=INK)
    ax.text(0.44, 0.835, r"$=$", ha="center", va="center", fontsize=9, color=INK)
    xs2 = draw_mps(ax, 0.20, 0.775, 7, bonds=[(1, ""), (4, "")], accent=BLUE)
    ax.text((xs2[1] + xs2[2]) / 2, 0.775 - 0.065, r"$V(g)^{-1}$", ha="center",
            fontsize=7.5, color=BLUE)
    ax.text((xs2[4] + xs2[5]) / 2, 0.775 - 0.065, r"$V(g)$", ha="center",
            fontsize=7.5, color=BLUE)
    ax.text(0.5, 0.660, r"$\mathcal{A}$:  charge algebra $\mathbb{C}_\omega[G]$ on the bonds;"
                        "\n" r"central extension $[\omega]=$ SPT index",
            ha="center", va="center", fontsize=7.5, color=INK)

    # --- corner C (bottom left): soft magnon displaced by 2 -----------------
    cx, cy = 0.185, 0.205
    xg = np.linspace(-0.15, 0.15, 400)
    env = np.exp(-(xg / 0.055) ** 2)
    ax.plot(cx + xg - 0.014, cy + 0.085 * env, color=MUTED, lw=0.8, ls="--",
            zorder=2)
    ax.plot(cx + xg - 0.058, cy + 0.085 * env * np.cos(xg / 0.011), color=ORANGE,
            lw=0.9, zorder=3)
    ax.annotate("", xy=(cx - 0.058, cy + 0.112), xytext=(cx - 0.014, cy + 0.112),
                arrowprops=dict(arrowstyle="-|>", lw=0.9, color=INK,
                                mutation_scale=8))
    ax.text(cx - 0.036, cy + 0.128, r"$2$ sites", ha="center", fontsize=7,
            color=INK)
    ax.text(cx, cy - 0.115,
            r"$\mathcal{C}$: soft theorem" "\n"
            r"$\delta=2k_s+\frac{v_h}{\omega_h}k_s^2+\dots$",
            ha="center", va="center", fontsize=7.5, color=INK)

    # --- corner B (bottom right): wall shifted by -2T -----------------------
    bx, by = 0.815, 0.205
    xw = np.linspace(-0.13, 0.13, 300)
    ax.plot(bx + xw, by + 0.055 * np.tanh((xw + 0.028) / 0.018), color=MUTED,
            lw=0.9, ls="--", zorder=2)
    ax.plot(bx + xw, by + 0.055 * np.tanh((xw - 0.000) / 0.018), color=AQUA,
            lw=1.1, zorder=3)
    ax.annotate("", xy=(bx - 0.028, by + 0.078), xytext=(bx + 0.000, by + 0.078),
                arrowprops=dict(arrowstyle="-|>", lw=0.9, color=INK,
                                mutation_scale=8))
    ax.text(bx - 0.014, by + 0.095, r"$\delta x=-2T$", ha="center", fontsize=7,
            color=INK)
    ax.text(bx, by - 0.115,
            r"$\mathcal{B}$: quantized memory" "\n"
            r"$T=1-[1+(4\omega v/J_\perp^2)^2]^{-1}$",
            ha="center", va="center", fontsize=7.5, color=INK)

    # --- edges --------------------------------------------------------------
    def edge(p, q, label, lx, ly, rad=0.18):
        ax.add_patch(FancyArrowPatch(p, q, connectionstyle=f"arc3,rad={rad}",
                                     arrowstyle="-|>", mutation_scale=7,
                                     lw=0.8, color=INK2, shrinkA=4, shrinkB=4))
        ax.text(lx, ly, label, fontsize=6.8, color=INK2, ha="center",
                va="center", rotation=0)
    edge((0.325, 0.62), (0.175, 0.36), "Ward identity\n+ contact term", 0.135, 0.505, rad=0.25)
    edge((0.32, 0.155), (0.66, 0.155), "DC flux limit", 0.492, 0.115, rad=-0.12)
    edge((0.845, 0.36), (0.685, 0.62), "superselection\nbookkeeping", 0.875, 0.505, rad=0.25)
    save(fig, "fig1")


if __name__ == "__main__":
    fig2()
    fig3()
    fig1()
